#cloud-config
# Copyright (c) 2017, cloudcodeit.com

## This Script will install
# - Support for SMB 3.0 File Share Mounts
# - Ansible
# - Ansible Azure Module Support

packages:
 - libssl-dev
 - libffi-dev
 - python-dev
 - build-essential
 - python-pip
 - ansible
 - cifs-utils

runcmd:
 - pip install --upgrade pip
 - pip install azure==2.0.0rc5 msrestazure dnspython
 - echo "Cloud-Init Completed -- $(date -R)!"
